### ISSUE TITLE
just build-grpc:  Explicit 'optional' labels are disallowed in the Proto3 syntax

### ISSUE THREAD

**Issue by kent-vsys** [devashishdxt/stag#25]
When running:
just build-grpc

Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
---

Problem solved by deleting "optional" in relevant proto code.

---
stderr in pastebin link below:
https://pastebin.com/3NqSQ3ha

**Comment by devashishdxt** [comment]
Can you provide the protoc version installed on your local machine?

```
protoc --version
```

**Comment by kent-vsys** [comment]
Running 2 instances with same problems:
1) Ubuntu 22.04.2 LTS, libprotoc 3.12.4
2) Ubuntu 20.04.6 LTS, libprotoc 3.6.1

**Comment by devashishdxt** [comment]
Can you upgrade your protoc version to latest and try again?

**Comment by devashishdxt** [comment]
Optional fields were enabled by default in `protoc v3.15.0`. Here are the release notes: https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0

**Comment by kent-vsys** [comment]
Yes thank you, updating protoc to the latest version resolved the error.

Next problem is just build-ui error.  I have installed node.js=18.16.0 ;
npm=9.5.1 ; wasm-pack=0.11.1 ; wasm-bindgen 0.2.86 ; ubuntu=20.04 and 22.04
---
***@***.***:~/stag# just build-ui
Building Stag UI...
cd stag-ui && trunk build
2023-06-09T08:15:17.316708Z  INFO 📦 starting build
2023-06-09T08:15:17.316898Z  INFO spawning asset pipelines
2023-06-09T08:15:17.316921Z  INFO spawned hook npx
command_arguments=["--yes", "tailwindcss", "--config",
"tailwind.config.js", "--input", "main.css", "--output", "tailwind.css",
"--minify"]
2023-06-09T08:15:17.316936Z  INFO spawning hook stage=PreBuild command=npx

Rebuilding...

Done in 335ms.
npm notice
npm notice New minor version of npm available! 9.5.1 -> 9.7.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.7.1
npm notice Run npm install -g ***@***.*** to update!
npm notice
2023-06-09T08:15:21.424522Z  INFO finished hook npx
2023-06-09T08:15:24.522489Z  INFO copying & hashing css path="tailwind.css"
2023-06-09T08:15:24.522496Z  INFO building stag-ui
2023-06-09T08:15:24.522676Z  INFO finished copying & hashing css
path="tailwind.css"
   Compiling proc-macro2 v1.0.50
   Compiling quote v1.0.23
   Compiling unicode-ident v1.0.6
   Compiling syn v1.0.107
   Compiling log v0.4.17
   Compiling cfg-if v1.0.0
error[E0463]: can't find crate for `core`
  |
  = note: the `wasm32-unknown-unknown` target may not be installed
  = help: consider downloading the target with `rustup target add
wasm32-unknown-unknown`

error[E0463]: can't find crate for `compiler_builtins`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `cfg-if` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
2023-06-09T08:15:31.616044Z ERROR ❌ error
error from HTML pipeline

Caused by:
    0: error from asset pipeline
    1: error during cargo build execution
    2: cargo call returned a bad status
Error: error from HTML pipeline

Caused by:
    0: error from asset pipeline
    1: error during cargo build execution
    2: cargo call returned a bad status
error: Recipe `build-ui` failed on line 34 with exit code 1

**Comment by kent-vsys** [comment]
Hi Devashish!

Hoping you can shed some light on the build-ui error that I have logged in
github.

Thanks in advance,

Kent
