### ISSUE TITLE
just build-grpc:  After removing "optional" from proto code to pass Proto3 syntax, 43 new errors revealed in stag-grpc v0.1.0

### ISSUE THREAD

**Issue by kent-vsys** [devashishdxt/stag#26]
After removing "optional" from proto code to pass Proto3 syntax 
(https://github.com/devashishdxt/stag/issues/25), 
43 new errors revealed in stag-grpc v0.1.0 when running:
just build-grpc

---
stderr sent to pastebin link below:
https://pastebin.com/eASTqXdp

**Comment by devashishdxt** [comment]
If you remove `optional` from proto files, you'll have to make necessary changes in the code as well. Closing this issue and tracking the build issue in #25.

**Comment by kent-vsys** [comment]
I have added libprotoc versions to comments.  Is there anything else I can
do to assist you?
